name: Test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version: 
          - 1.19.x
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@master
    - name: Test
      run: go test ./...
