name: Test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version-file: go.mod
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: go test ./...
